// --- 母音マップ ---
export const vM={'あ':'a','か':'a','さ':'a','た':'a','な':'a','は':'a','ま':'a','や':'a','ら':'a','わ':'a','が':'a','ざ':'a','だ':'a','ば':'a','ぱ':'a','ぁ':'a','ゃ':'a','い':'i','き':'i','し':'i','ち':'i','に':'i','ひ':'i','み':'i','り':'i','ぎ':'i','じ':'i','ぢ':'i','び':'i','ぴ':'i','ぃ':'i','う':'u','く':'u','す':'u','つ':'u','ぬ':'u','ふ':'u','む':'u','ゆ':'u','る':'u','ぐ':'u','ず':'u','づ':'u','ぶ':'u','ぷ':'u','ぅ':'u','ゅ':'u','え':'e','け':'e','せ':'e','て':'e','ね':'e','へ':'e','め':'e','れ':'e','げ':'e','ぜ':'e','で':'e','べ':'e','ぺ':'e','ぇ':'e','お':'o','こ':'o','そ':'o','と':'o','の':'o','ほ':'o','も':'o','よ':'o','ろ':'o','を':'o','ご':'o','ぞ':'o','ど':'o','ぼ':'o','ぽ':'o','ぉ':'o','ょ':'o','ん':'n','ー':'-'};

// --- 母音抽出（っ吸収対応）---
export function pv(s){
    // っ・ッを直前の音に吸収（音数カウントから除外）
    s=s.replace(/[っッ](?=[ぁ-んァ-ン])/g,'');
    s=s.replace(/[っッ]/g,'');
    let r=[];
    for(let c of s){if(vM[c])r.push(vM[c]);}
    return r;
}

// --- LYRIC_WORDS（品詞付き・約1500語）---
export const LYRIC_WORDS=[
// ===== 名詞 =====
{word:'愛',pos:'名詞'},{word:'恋',pos:'名詞'},{word:'夢',pos:'名詞'},{word:'希望',pos:'名詞'},{word:'孤独',pos:'名詞'},
{word:'痛み',pos:'名詞'},{word:'悲しみ',pos:'名詞'},{word:'喜び',pos:'名詞'},{word:'怒り',pos:'名詞'},{word:'恐れ',pos:'名詞'},
{word:'不安',pos:'名詞'},{word:'安らぎ',pos:'名詞'},{word:'切なさ',pos:'名詞'},{word:'憧れ',pos:'名詞'},{word:'後悔',pos:'名詞'},
{word:'誇り',pos:'名詞'},{word:'嫉妬',pos:'名詞'},{word:'感謝',pos:'名詞'},{word:'信頼',pos:'名詞'},{word:'絶望',pos:'名詞'},
{word:'勇気',pos:'名詞'},{word:'優しさ',pos:'名詞'},{word:'強さ',pos:'名詞'},{word:'弱さ',pos:'名詞'},{word:'迷い',pos:'名詞'},
{word:'覚悟',pos:'名詞'},{word:'諦め',pos:'名詞'},{word:'執着',pos:'名詞'},{word:'解放',pos:'名詞'},{word:'癒し',pos:'名詞'},
{word:'傷',pos:'名詞'},{word:'想い',pos:'名詞'},{word:'気持ち',pos:'名詞'},{word:'感情',pos:'名詞'},{word:'心',pos:'名詞'},
{word:'魂',pos:'名詞'},{word:'意志',pos:'名詞'},{word:'本音',pos:'名詞'},{word:'嘘',pos:'名詞'},{word:'真実',pos:'名詞'},
{word:'秘密',pos:'名詞'},{word:'告白',pos:'名詞'},{word:'誓い',pos:'名詞'},{word:'祈り',pos:'名詞'},{word:'願い',pos:'名詞'},
{word:'空',pos:'名詞'},{word:'海',pos:'名詞'},{word:'山',pos:'名詞'},{word:'川',pos:'名詞'},{word:'森',pos:'名詞'},
{word:'砂漠',pos:'名詞'},{word:'草原',pos:'名詞'},{word:'大地',pos:'名詞'},{word:'宇宙',pos:'名詞'},{word:'星',pos:'名詞'},
{word:'月',pos:'名詞'},{word:'太陽',pos:'名詞'},{word:'雲',pos:'名詞'},{word:'雨',pos:'名詞'},{word:'雪',pos:'名詞'},
{word:'風',pos:'名詞'},{word:'嵐',pos:'名詞'},{word:'雷',pos:'名詞'},{word:'霧',pos:'名詞'},{word:'虹',pos:'名詞'},
{word:'波',pos:'名詞'},{word:'砂',pos:'名詞'},{word:'岩',pos:'名詞'},{word:'土',pos:'名詞'},{word:'花',pos:'名詞'},
{word:'桜',pos:'名詞'},{word:'薔薇',pos:'名詞'},{word:'葉',pos:'名詞'},{word:'木',pos:'名詞'},{word:'根',pos:'名詞'},
{word:'種',pos:'名詞'},{word:'枝',pos:'名詞'},{word:'幹',pos:'名詞'},{word:'光',pos:'名詞'},{word:'闇',pos:'名詞'},
{word:'影',pos:'名詞'},{word:'炎',pos:'名詞'},{word:'火',pos:'名詞'},{word:'水',pos:'名詞'},{word:'氷',pos:'名詞'},
{word:'霜',pos:'名詞'},{word:'露',pos:'名詞'},{word:'泡',pos:'名詞'},{word:'煙',pos:'名詞'},{word:'灰',pos:'名詞'},
{word:'夜空',pos:'名詞'},{word:'朝焼け',pos:'名詞'},{word:'夕焼け',pos:'名詞'},{word:'夜明け',pos:'名詞'},{word:'夕暮れ',pos:'名詞'},
{word:'黄昏',pos:'名詞'},{word:'夜',pos:'名詞'},{word:'朝',pos:'名詞'},{word:'昼',pos:'名詞'},{word:'地平線',pos:'名詞'},
{word:'水平線',pos:'名詞'},{word:'彼方',pos:'名詞'},{word:'果て',pos:'名詞'},{word:'今',pos:'名詞'},{word:'昨日',pos:'名詞'},
{word:'明日',pos:'名詞'},{word:'過去',pos:'名詞'},{word:'未来',pos:'名詞'},{word:'現在',pos:'名詞'},{word:'永遠',pos:'名詞'},
{word:'瞬間',pos:'名詞'},{word:'時間',pos:'名詞'},{word:'時',pos:'名詞'},{word:'刻',pos:'名詞'},{word:'季節',pos:'名詞'},
{word:'春',pos:'名詞'},{word:'夏',pos:'名詞'},{word:'秋',pos:'名詞'},{word:'冬',pos:'名詞'},{word:'記憶',pos:'名詞'},
{word:'始まり',pos:'名詞'},{word:'終わり',pos:'名詞'},{word:'声',pos:'名詞'},{word:'手',pos:'名詞'},{word:'目',pos:'名詞'},
{word:'息',pos:'名詞'},{word:'涙',pos:'名詞'},{word:'鼓動',pos:'名詞'},{word:'血',pos:'名詞'},{word:'肌',pos:'名詞'},
{word:'唇',pos:'名詞'},{word:'髪',pos:'名詞'},{word:'胸',pos:'名詞'},{word:'背',pos:'名詞'},{word:'腕',pos:'名詞'},
{word:'指',pos:'名詞'},{word:'耳',pos:'名詞'},{word:'体',pos:'名詞'},{word:'命',pos:'名詞'},{word:'生',pos:'名詞'},
{word:'死',pos:'名詞'},{word:'温もり',pos:'名詞'},{word:'香り',pos:'名詞'},{word:'音',pos:'名詞'},{word:'色',pos:'名詞'},
{word:'街',pos:'名詞'},{word:'部屋',pos:'名詞'},{word:'家',pos:'名詞'},{word:'扉',pos:'名詞'},{word:'窓',pos:'名詞'},
{word:'道',pos:'名詞'},{word:'橋',pos:'名詞'},{word:'坂',pos:'名詞'},{word:'駅',pos:'名詞'},{word:'空港',pos:'名詞'},
{word:'港',pos:'名詞'},{word:'海岸',pos:'名詞'},{word:'浜辺',pos:'名詞'},{word:'岸',pos:'名詞'},{word:'崖',pos:'名詞'},
{word:'丘',pos:'名詞'},{word:'谷',pos:'名詞'},{word:'廃墟',pos:'名詞'},{word:'屋上',pos:'名詞'},{word:'遠く',pos:'名詞'},
{word:'故郷',pos:'名詞'},{word:'帰り道',pos:'名詞'},{word:'出口',pos:'名詞'},{word:'入口',pos:'名詞'},{word:'境界',pos:'名詞'},
{word:'歌',pos:'名詞'},{word:'沈黙',pos:'名詞'},{word:'出会い',pos:'名詞'},{word:'別れ',pos:'名詞'},{word:'抱擁',pos:'名詞'},
{word:'言葉',pos:'名詞'},{word:'詩',pos:'名詞'},{word:'音楽',pos:'名詞'},{word:'意味',pos:'名詞'},{word:'存在',pos:'名詞'},
{word:'繋がり',pos:'名詞'},{word:'絆',pos:'名詞'},{word:'縁',pos:'名詞'},{word:'運命',pos:'名詞'},{word:'奇跡',pos:'名詞'},
{word:'祝福',pos:'名詞'},{word:'救い',pos:'名詞'},{word:'変化',pos:'名詞'},{word:'成長',pos:'名詞'},{word:'再生',pos:'名詞'},
{word:'自由',pos:'名詞'},{word:'限界',pos:'名詞'},{word:'可能性',pos:'名詞'},{word:'君',pos:'名詞'},{word:'僕',pos:'名詞'},
{word:'私',pos:'名詞'},{word:'彼',pos:'名詞'},{word:'彼女',pos:'名詞'},{word:'友',pos:'名詞'},{word:'仲間',pos:'名詞'},
{word:'恋人',pos:'名詞'},{word:'家族',pos:'名詞'},{word:'親',pos:'名詞'},{word:'子',pos:'名詞'},{word:'誰か',pos:'名詞'},
{word:'ひとり',pos:'名詞'},{word:'ふたり',pos:'名詞'},{word:'再会',pos:'名詞'},{word:'約束',pos:'名詞'},{word:'裏切り',pos:'名詞'},
{word:'理解',pos:'名詞'},{word:'孤立',pos:'名詞'},{word:'真夜中',pos:'名詞'},{word:'明け方',pos:'名詞'},{word:'朝靄',pos:'名詞'},
{word:'月明かり',pos:'名詞'},{word:'木漏れ日',pos:'名詞'},{word:'波紋',pos:'名詞'},{word:'水面',pos:'名詞'},{word:'断片',pos:'名詞'},
{word:'欠片',pos:'名詞'},{word:'痕跡',pos:'名詞'},{word:'足跡',pos:'名詞'},{word:'傷跡',pos:'名詞'},{word:'白昼夢',pos:'名詞'},
{word:'悪夢',pos:'名詞'},{word:'翼',pos:'名詞'},{word:'羽根',pos:'名詞'},{word:'天空',pos:'名詞'},{word:'深淵',pos:'名詞'},
{word:'砂粒',pos:'名詞'},{word:'水滴',pos:'名詞'},{word:'雪片',pos:'名詞'},{word:'花びら',pos:'名詞'},{word:'蕾',pos:'名詞'},
{word:'開花',pos:'名詞'},{word:'霊',pos:'名詞'},{word:'意識',pos:'名詞'},{word:'本能',pos:'名詞'},{word:'理性',pos:'名詞'},
{word:'直感',pos:'名詞'},{word:'予感',pos:'名詞'},{word:'メロディ',pos:'名詞'},{word:'リズム',pos:'名詞'},{word:'余韻',pos:'名詞'},
{word:'静寂',pos:'名詞'},{word:'旋律',pos:'名詞'},{word:'調べ',pos:'名詞'},{word:'輝き',pos:'名詞'},{word:'残像',pos:'名詞'},
{word:'幻影',pos:'名詞'},{word:'煌めき',pos:'名詞'},{word:'揺らめき',pos:'名詞'},{word:'さざ波',pos:'名詞'},{word:'微笑み',pos:'名詞'},
{word:'嘆き',pos:'名詞'},{word:'語り',pos:'名詞'},{word:'甘さ',pos:'名詞'},{word:'苦さ',pos:'名詞'},{word:'儚さ',pos:'名詞'},
{word:'深さ',pos:'名詞'},{word:'広さ',pos:'名詞'},{word:'高さ',pos:'名詞'},{word:'速さ',pos:'名詞'},{word:'明るさ',pos:'名詞'},
{word:'静けさ',pos:'名詞'},{word:'美しさ',pos:'名詞'},{word:'純粋さ',pos:'名詞'},{word:'複雑さ',pos:'名詞'},{word:'闇夜',pos:'名詞'},
{word:'霞',pos:'名詞'},{word:'鏡',pos:'名詞'},{word:'空白',pos:'名詞'},{word:'余白',pos:'名詞'},{word:'隙間',pos:'名詞'},
{word:'裂け目',pos:'名詞'},{word:'狭間',pos:'名詞'},{word:'螺旋',pos:'名詞'},{word:'渦',pos:'名詞'},{word:'循環',pos:'名詞'},
{word:'虚無',pos:'名詞'},{word:'混沌',pos:'名詞'},{word:'秩序',pos:'名詞'},{word:'調和',pos:'名詞'},{word:'共鳴',pos:'名詞'},
{word:'反響',pos:'名詞'},{word:'木霊',pos:'名詞'},{word:'灯り',pos:'名詞'},{word:'蛍',pos:'名詞'},{word:'閃光',pos:'名詞'},
{word:'幻',pos:'名詞'},{word:'影法師',pos:'名詞'},{word:'残り香',pos:'名詞'},{word:'面影',pos:'名詞'},{word:'余韻',pos:'名詞'},
{word:'哀愁',pos:'名詞'},{word:'郷愁',pos:'名詞'},{word:'望郷',pos:'名詞'},{word:'旅路',pos:'名詞'},{word:'旅人',pos:'名詞'},
{word:'旅',pos:'名詞'},{word:'行方',pos:'名詞'},{word:'行く先',pos:'名詞'},{word:'終点',pos:'名詞'},{word:'起点',pos:'名詞'},
{word:'原点',pos:'名詞'},{word:'頂点',pos:'名詞'},{word:'底辺',pos:'名詞'},{word:'地底',pos:'名詞'},{word:'地上',pos:'名詞'},
{word:'天上',pos:'名詞'},{word:'天国',pos:'名詞'},{word:'地獄',pos:'名詞'},{word:'楽園',pos:'名詞'},{word:'異世界',pos:'名詞'},
{word:'現実',pos:'名詞'},{word:'幻想',pos:'名詞'},{word:'理想',pos:'名詞'},{word:'妄想',pos:'名詞'},{word:'空想',pos:'名詞'},
{word:'白',pos:'名詞'},{word:'黒',pos:'名詞'},{word:'赤',pos:'名詞'},{word:'青',pos:'名詞'},{word:'緑',pos:'名詞'},
{word:'金',pos:'名詞'},{word:'銀',pos:'名詞'},{word:'蒼',pos:'名詞'},{word:'紅',pos:'名詞'},{word:'漆黒',pos:'名詞'},
{word:'純白',pos:'名詞'},{word:'陽光',pos:'名詞'},{word:'月光',pos:'名詞'},{word:'星光',pos:'名詞'},{word:'薄明',pos:'名詞'},
{word:'残光',pos:'名詞'},{word:'暁',pos:'名詞'},{word:'宵',pos:'名詞'},{word:'夕',pos:'名詞'},{word:'朝露',pos:'名詞'},
{word:'夜露',pos:'名詞'},{word:'霙',pos:'名詞'},{word:'霰',pos:'名詞'},{word:'吹雪',pos:'名詞'},{word:'春風',pos:'名詞'},
{word:'夜風',pos:'名詞'},{word:'潮風',pos:'名詞'},{word:'海風',pos:'名詞'},{word:'山風',pos:'名詞'},{word:'木の葉',pos:'名詞'},
{word:'落ち葉',pos:'名詞'},{word:'枯れ葉',pos:'名詞'},{word:'新芽',pos:'名詞'},{word:'若葉',pos:'名詞'},{word:'青葉',pos:'名詞'},
{word:'紅葉',pos:'名詞'},{word:'雑踏',pos:'名詞'},{word:'人混み',pos:'名詞'},{word:'喧噪',pos:'名詞'},{word:'喧嘩',pos:'名詞'},
{word:'涙雨',pos:'名詞'},{word:'通り雨',pos:'名詞'},{word:'夕立',pos:'名詞'},{word:'霧雨',pos:'名詞'},{word:'小雨',pos:'名詞'},
{word:'大雨',pos:'名詞'},{word:'豪雨',pos:'名詞'},{word:'春雨',pos:'名詞'},{word:'梅雨',pos:'名詞'},{word:'雨粒',pos:'名詞'},
{word:'雨音',pos:'名詞'},{word:'波音',pos:'名詞'},{word:'風音',pos:'名詞'},{word:'足音',pos:'名詞'},{word:'笑い声',pos:'名詞'},
{word:'泣き声',pos:'名詞'},{word:'叫び声',pos:'名詞'},{word:'囁き',pos:'名詞'},{word:'溜息',pos:'名詞'},{word:'吐息',pos:'名詞'},
{word:'心音',pos:'名詞'},{word:'拍動',pos:'名詞'},{word:'脈',pos:'名詞'},{word:'呼吸',pos:'名詞'},{word:'鼓動',pos:'名詞'},
{word:'瞬き',pos:'名詞'},{word:'まなざし',pos:'名詞'},{word:'眼差し',pos:'名詞'},{word:'視線',pos:'名詞'},{word:'視界',pos:'名詞'},
{word:'景色',pos:'名詞'},{word:'風景',pos:'名詞'},{word:'情景',pos:'名詞'},{word:'光景',pos:'名詞'},{word:'場面',pos:'名詞'},
{word:'夢見',pos:'名詞'},{word:'寝顔',pos:'名詞'},{word:'笑顔',pos:'名詞'},{word:'泣き顔',pos:'名詞'},{word:'横顔',pos:'名詞'},
{word:'後ろ姿',pos:'名詞'},{word:'後姿',pos:'名詞'},{word:'立ち姿',pos:'名詞'},{word:'佇まい',pos:'名詞'},{word:'面影',pos:'名詞'},
{word:'思い出',pos:'名詞'},{word:'懐かしさ',pos:'名詞'},{word:'昔',pos:'名詞'},{word:'あの頃',pos:'名詞'},{word:'幼い頃',pos:'名詞'},
{word:'子供の頃',pos:'名詞'},{word:'青春',pos:'名詞'},{word:'青年',pos:'名詞'},{word:'少女',pos:'名詞'},{word:'少年',pos:'名詞'},
{word:'大人',pos:'名詞'},{word:'老い',pos:'名詞'},{word:'年齢',pos:'名詞'},{word:'世代',pos:'名詞'},{word:'時代',pos:'名詞'},
{word:'世界',pos:'名詞'},{word:'国',pos:'名詞'},{word:'地球',pos:'名詞'},{word:'自然',pos:'名詞'},{word:'生命',pos:'名詞'},
{word:'生き物',pos:'名詞'},{word:'動物',pos:'名詞'},{word:'鳥',pos:'名詞'},{word:'魚',pos:'名詞'},{word:'虫',pos:'名詞'},
// ===== 動詞（辞書形）=====
{word:'変わる',pos:'動詞'},{word:'回る',pos:'動詞'},{word:'触る',pos:'動詞'},{word:'走る',pos:'動詞'},{word:'飛ぶ',pos:'動詞'},
{word:'消える',pos:'動詞'},{word:'輝く',pos:'動詞'},{word:'流れる',pos:'動詞'},{word:'泣く',pos:'動詞'},{word:'笑う',pos:'動詞'},
{word:'歌う',pos:'動詞'},{word:'叫ぶ',pos:'動詞'},{word:'囁く',pos:'動詞'},{word:'語る',pos:'動詞'},{word:'伝える',pos:'動詞'},
{word:'届く',pos:'動詞'},{word:'響く',pos:'動詞'},{word:'揺れる',pos:'動詞'},{word:'震える',pos:'動詞'},{word:'溶ける',pos:'動詞'},
{word:'凍る',pos:'動詞'},{word:'燃える',pos:'動詞'},{word:'咲く',pos:'動詞'},{word:'散る',pos:'動詞'},{word:'枯れる',pos:'動詞'},
{word:'生まれる',pos:'動詞'},{word:'死ぬ',pos:'動詞'},{word:'生きる',pos:'動詞'},{word:'消す',pos:'動詞'},{word:'壊れる',pos:'動詞'},
{word:'壊す',pos:'動詞'},{word:'作る',pos:'動詞'},{word:'描く',pos:'動詞'},{word:'奏でる',pos:'動詞'},{word:'踊る',pos:'動詞'},
{word:'跳ねる',pos:'動詞'},{word:'滑る',pos:'動詞'},{word:'転がる',pos:'動詞'},{word:'浮かぶ',pos:'動詞'},{word:'沈む',pos:'動詞'},
{word:'漂う',pos:'動詞'},{word:'流す',pos:'動詞'},{word:'落ちる',pos:'動詞'},{word:'上がる',pos:'動詞'},{word:'下がる',pos:'動詞'},
{word:'広がる',pos:'動詞'},{word:'縮まる',pos:'動詞'},{word:'伸びる',pos:'動詞'},{word:'縮む',pos:'動詞'},{word:'重なる',pos:'動詞'},
{word:'離れる',pos:'動詞'},{word:'近づく',pos:'動詞'},{word:'遠ざかる',pos:'動詞'},{word:'追いかける',pos:'動詞'},{word:'逃げる',pos:'動詞'},
{word:'探す',pos:'動詞'},{word:'見つける',pos:'動詞'},{word:'失う',pos:'動詞'},{word:'忘れる',pos:'動詞'},{word:'思い出す',pos:'動詞'},
{word:'覚える',pos:'動詞'},{word:'知る',pos:'動詞'},{word:'気づく',pos:'動詞'},{word:'感じる',pos:'動詞'},{word:'考える',pos:'動詞'},
{word:'信じる',pos:'動詞'},{word:'疑う',pos:'動詞'},{word:'願う',pos:'動詞'},{word:'祈る',pos:'動詞'},{word:'誓う',pos:'動詞'},
{word:'愛する',pos:'動詞'},{word:'憎む',pos:'動詞'},{word:'許す',pos:'動詞'},{word:'傷つける',pos:'動詞'},{word:'癒す',pos:'動詞'},
{word:'助ける',pos:'動詞'},{word:'守る',pos:'動詞'},{word:'壊す',pos:'動詞'},{word:'奪う',pos:'動詞'},{word:'与える',pos:'動詞'},
{word:'受け取る',pos:'動詞'},{word:'手放す',pos:'動詞'},{word:'掴む',pos:'動詞'},{word:'握る',pos:'動詞'},{word:'解く',pos:'動詞'},
{word:'繋ぐ',pos:'動詞'},{word:'切る',pos:'動詞'},{word:'結ぶ',pos:'動詞'},{word:'開く',pos:'動詞'},{word:'閉じる',pos:'動詞'},
{word:'始まる',pos:'動詞'},{word:'終わる',pos:'動詞'},{word:'続く',pos:'動詞'},{word:'止まる',pos:'動詞'},{word:'進む',pos:'動詞'},
{word:'戻る',pos:'動詞'},{word:'帰る',pos:'動詞'},{word:'向かう',pos:'動詞'},{word:'辿る',pos:'動詞'},{word:'迷う',pos:'動詞'},
{word:'立つ',pos:'動詞'},{word:'座る',pos:'動詞'},{word:'眠る',pos:'動詞'},{word:'目覚める',pos:'動詞'},{word:'待つ',pos:'動詞'},
{word:'呼ぶ',pos:'動詞'},{word:'答える',pos:'動詞'},{word:'聞く',pos:'動詞'},{word:'見る',pos:'動詞'},{word:'触れる',pos:'動詞'},
{word:'抱く',pos:'動詞'},{word:'離す',pos:'動詞'},{word:'押す',pos:'動詞'},{word:'引く',pos:'動詞'},{word:'投げる',pos:'動詞'},
{word:'受ける',pos:'動詞'},{word:'避ける',pos:'動詞'},{word:'向き合う',pos:'動詞'},{word:'背を向ける',pos:'動詞'},{word:'振り返る',pos:'動詞'},
{word:'見上げる',pos:'動詞'},{word:'見下ろす',pos:'動詞'},{word:'見送る',pos:'動詞'},{word:'見守る',pos:'動詞'},{word:'見つめる',pos:'動詞'},
{word:'照らす',pos:'動詞'},{word:'隠す',pos:'動詞'},{word:'現れる',pos:'動詞'},{word:'消し去る',pos:'動詞'},{word:'蘇る',pos:'動詞'},
{word:'変える',pos:'動詞'},{word:'壊れていく',pos:'動詞'},{word:'溢れる',pos:'動詞'},{word:'枯らす',pos:'動詞'},{word:'育てる',pos:'動詞'},
{word:'育つ',pos:'動詞'},{word:'芽吹く',pos:'動詞'},{word:'実る',pos:'動詞'},{word:'こぼれる',pos:'動詞'},{word:'滲む',pos:'動詞'},
{word:'霞む',pos:'動詞'},{word:'滲んでく',pos:'動詞'},{word:'揺らぐ',pos:'動詞'},{word:'揺さぶる',pos:'動詞'},{word:'崩れる',pos:'動詞'},
{word:'砕ける',pos:'動詞'},{word:'割れる',pos:'動詞'},{word:'裂ける',pos:'動詞'},{word:'解ける',pos:'動詞'},{word:'結ばれる',pos:'動詞'},
{word:'交わる',pos:'動詞'},{word:'混じる',pos:'動詞'},{word:'溶け合う',pos:'動詞'},{word:'重なり合う',pos:'動詞'},{word:'響き合う',pos:'動詞'},
{word:'惹かれる',pos:'動詞'},{word:'引き寄せる',pos:'動詞'},{word:'突き放す',pos:'動詞'},{word:'引き止める',pos:'動詞'},{word:'手を伸ばす',pos:'動詞'},
{word:'走り出す',pos:'動詞'},{word:'飛び出す',pos:'動詞'},{word:'踏み出す',pos:'動詞'},{word:'立ち上がる',pos:'動詞'},{word:'倒れる',pos:'動詞'},
{word:'折れる',pos:'動詞'},{word:'曲がる',pos:'動詞'},{word:'伸ばす',pos:'動詞'},{word:'包む',pos:'動詞'},{word:'纏う',pos:'動詞'},
{word:'剥がれる',pos:'動詞'},{word:'重ねる',pos:'動詞'},{word:'積み上げる',pos:'動詞'},{word:'崩す',pos:'動詞'},{word:'積もる',pos:'動詞'},
{word:'染まる',pos:'動詞'},{word:'染める',pos:'動詞'},{word:'色づく',pos:'動詞'},{word:'褪せる',pos:'動詞'},{word:'輝かせる',pos:'動詞'},
{word:'照り輝く',pos:'動詞'},{word:'瞬く',pos:'動詞'},{word:'きらめく',pos:'動詞'},{word:'ざわめく',pos:'動詞'},{word:'さざめく',pos:'動詞'},
{word:'囲む',pos:'動詞'},{word:'包み込む',pos:'動詞'},{word:'満たす',pos:'動詞'},{word:'満ちる',pos:'動詞'},{word:'空く',pos:'動詞'},
{word:'埋まる',pos:'動詞'},{word:'埋める',pos:'動詞'},{word:'満ちあふれる',pos:'動詞'},{word:'こぼれ落ちる',pos:'動詞'},{word:'流れ落ちる',pos:'動詞'},
{word:'降り注ぐ',pos:'動詞'},{word:'降り積もる',pos:'動詞'},{word:'舞い散る',pos:'動詞'},{word:'舞い上がる',pos:'動詞'},{word:'舞い降りる',pos:'動詞'},
{word:'降る',pos:'動詞'},{word:'昇る',pos:'動詞'},{word:'沈んでく',pos:'動詞'},{word:'浮き上がる',pos:'動詞'},{word:'引き込まれる',pos:'動詞'},
{word:'吸い込まれる',pos:'動詞'},{word:'押し流される',pos:'動詞'},{word:'さらわれる',pos:'動詞'},{word:'溺れる',pos:'動詞'},{word:'泳ぐ',pos:'動詞'},
{word:'飛び越える',pos:'動詞'},{word:'乗り越える',pos:'動詞'},{word:'超える',pos:'動詞'},{word:'越えていく',pos:'動詞'},{word:'繰り返す',pos:'動詞'},
// ===== 形容詞 =====
{word:'遠い',pos:'形容詞'},{word:'近い',pos:'形容詞'},{word:'深い',pos:'形容詞'},{word:'浅い',pos:'形容詞'},{word:'高い',pos:'形容詞'},
{word:'低い',pos:'形容詞'},{word:'広い',pos:'形容詞'},{word:'狭い',pos:'形容詞'},{word:'大きい',pos:'形容詞'},{word:'小さい',pos:'形容詞'},
{word:'重い',pos:'形容詞'},{word:'軽い',pos:'形容詞'},{word:'速い',pos:'形容詞'},{word:'遅い',pos:'形容詞'},{word:'強い',pos:'形容詞'},
{word:'弱い',pos:'形容詞'},{word:'明るい',pos:'形容詞'},{word:'暗い',pos:'形容詞'},{word:'白い',pos:'形容詞'},{word:'黒い',pos:'形容詞'},
{word:'赤い',pos:'形容詞'},{word:'青い',pos:'形容詞'},{word:'淡い',pos:'形容詞'},{word:'鮮やかな',pos:'形容詞'},{word:'柔らかい',pos:'形容詞'},
{word:'硬い',pos:'形容詞'},{word:'温かい',pos:'形容詞'},{word:'冷たい',pos:'形容詞'},{word:'甘い',pos:'形容詞'},{word:'苦い',pos:'形容詞'},
{word:'辛い',pos:'形容詞'},{word:'儚い',pos:'形容詞'},{word:'寂しい',pos:'形容詞'},{word:'楽しい',pos:'形容詞'},{word:'悲しい',pos:'形容詞'},
{word:'切ない',pos:'形容詞'},{word:'懐かしい',pos:'形容詞'},{word:'新しい',pos:'形容詞'},{word:'古い',pos:'形容詞'},{word:'純粋な',pos:'形容詞'},
{word:'不思議な',pos:'形容詞'},{word:'眩しい',pos:'形容詞'},{word:'美しい',pos:'形容詞'},{word:'醜い',pos:'形容詞'},{word:'丸い',pos:'形容詞'},
{word:'細い',pos:'形容詞'},{word:'太い',pos:'形容詞'},{word:'長い',pos:'形容詞'},{word:'短い',pos:'形容詞'},{word:'若い',pos:'形容詞'},
{word:'古びた',pos:'形容詞'},{word:'新鮮な',pos:'形容詞'},{word:'鋭い',pos:'形容詞'},{word:'鈍い',pos:'形容詞'},{word:'激しい',pos:'形容詞'},
{word:'穏やかな',pos:'形容詞'},{word:'静かな',pos:'形容詞'},{word:'騒がしい',pos:'形容詞'},{word:'賑やかな',pos:'形容詞'},{word:'空虚な',pos:'形容詞'},
{word:'満ちた',pos:'形容詞'},{word:'空っぽな',pos:'形容詞'},{word:'複雑な',pos:'形容詞'},{word:'単純な',pos:'形容詞'},{word:'神秘的な',pos:'形容詞'},
{word:'幻想的な',pos:'形容詞'},{word:'透明な',pos:'形容詞'},{word:'曖昧な',pos:'形容詞'},{word:'確かな',pos:'形容詞'},{word:'脆い',pos:'形容詞'},
{word:'固い',pos:'形容詞'},{word:'優しい',pos:'形容詞'},{word:'厳しい',pos:'形容詞'},{word:'辛抱強い',pos:'形容詞'},{word:'気高い',pos:'形容詞'},
{word:'いとしい',pos:'形容詞'},{word:'恋しい',pos:'形容詞'},{word:'愛しい',pos:'形容詞'},{word:'憎い',pos:'形容詞'},{word:'怖い',pos:'形容詞'},
{word:'恐ろしい',pos:'形容詞'},{word:'頼もしい',pos:'形容詞'},{word:'心強い',pos:'形容詞'},{word:'心細い',pos:'形容詞'},{word:'むなしい',pos:'形容詞'},
{word:'はかない',pos:'形容詞'},{word:'あたたかい',pos:'形容詞'},{word:'ぬくもりある',pos:'形容詞'},{word:'涼しい',pos:'形容詞'},{word:'肌寒い',pos:'形容詞'},
// ===== 副詞 =====
{word:'ずっと',pos:'副詞'},{word:'もう',pos:'副詞'},{word:'まだ',pos:'副詞'},{word:'やがて',pos:'副詞'},{word:'ついに',pos:'副詞'},
{word:'ようやく',pos:'副詞'},{word:'いつか',pos:'副詞'},{word:'いつも',pos:'副詞'},{word:'きっと',pos:'副詞'},{word:'たぶん',pos:'副詞'},
{word:'もしも',pos:'副詞'},{word:'ただ',pos:'副詞'},{word:'そっと',pos:'副詞'},{word:'じっと',pos:'副詞'},{word:'ぼんやり',pos:'副詞'},
{word:'はっきり',pos:'副詞'},{word:'ゆっくり',pos:'副詞'},{word:'そろそろ',pos:'副詞'},{word:'だんだん',pos:'副詞'},{word:'どんどん',pos:'副詞'},
{word:'ふと',pos:'副詞'},{word:'突然',pos:'副詞'},{word:'静かに',pos:'副詞'},{word:'激しく',pos:'副詞'},{word:'優しく',pos:'副詞'},
{word:'強く',pos:'副詞'},{word:'深く',pos:'副詞'},{word:'遠く',pos:'副詞'},{word:'近くに',pos:'副詞'},{word:'高く',pos:'副詞'},
{word:'低く',pos:'副詞'},{word:'広く',pos:'副詞'},{word:'永遠に',pos:'副詞'},{word:'決して',pos:'副詞'},{word:'絶対に',pos:'副詞'},
{word:'少しずつ',pos:'副詞'},{word:'徐々に',pos:'副詞'},{word:'瞬く間に',pos:'副詞'},{word:'あっという間に',pos:'副詞'},{word:'いつの間にか',pos:'副詞'},
{word:'気づけば',pos:'副詞'},{word:'知らぬ間に',pos:'副詞'},{word:'無意識に',pos:'副詞'},{word:'自然と',pos:'副詞'},{word:'ひっそりと',pos:'副詞'},
{word:'こっそりと',pos:'副詞'},{word:'あふれるほど',pos:'副詞'},{word:'満ちるほど',pos:'副詞'},{word:'燃えるように',pos:'副詞'},{word:'溶けるように',pos:'副詞'},
{word:'もっと',pos:'副詞'},{word:'もっとも',pos:'副詞'},{word:'もはや',pos:'副詞'},{word:'もしかして',pos:'副詞'},{word:'きっかり',pos:'副詞'},
{word:'ぴたりと',pos:'副詞'},{word:'ふわりと',pos:'副詞'},{word:'するりと',pos:'副詞'},{word:'さらりと',pos:'副詞'},{word:'ざわりと',pos:'副詞'},
{word:'しんと',pos:'副詞'},{word:'がらんと',pos:'副詞'},{word:'ひんやりと',pos:'副詞'},{word:'ぽつりと',pos:'副詞'},{word:'ぽつんと',pos:'副詞'},
{word:'じわりと',pos:'副詞'},{word:'ほんのり',pos:'副詞'},{word:'うっすらと',pos:'副詞'},{word:'うっかり',pos:'副詞'},{word:'すっかり',pos:'副詞'},
{word:'すっきり',pos:'副詞'},{word:'ぼろぼろと',pos:'副詞'},{word:'ひらひらと',pos:'副詞'},{word:'ゆらゆらと',pos:'副詞'},{word:'くるくると',pos:'副詞'},
// ===== 名詞追加 =====
{word:'砂時計',pos:'名詞'},{word:'砂漠',pos:'名詞'},{word:'蜃気楼',pos:'名詞'},{word:'蜘蛛の巣',pos:'名詞'},{word:'迷宮',pos:'名詞'},
{word:'宝物',pos:'名詞'},{word:'宝箱',pos:'名詞'},{word:'鍵',pos:'名詞'},{word:'錠前',pos:'名詞'},{word:'地図',pos:'名詞'},
{word:'羅針盤',pos:'名詞'},{word:'灯台',pos:'名詞'},{word:'燈火',pos:'名詞'},{word:'篝火',pos:'名詞'},{word:'焚き火',pos:'名詞'},
{word:'煙突',pos:'名詞'},{word:'時計',pos:'名詞'},{word:'砂鉄',pos:'名詞'},{word:'鉄錆',pos:'名詞'},{word:'ガラス',pos:'名詞'},
{word:'鎖',pos:'名詞'},{word:'檻',pos:'名詞'},{word:'牢',pos:'名詞'},{word:'城',pos:'名詞'},{word:'塔',pos:'名詞'},
{word:'砦',pos:'名詞'},{word:'廃城',pos:'名詞'},{word:'神殿',pos:'名詞'},{word:'祭壇',pos:'名詞'},{word:'聖地',pos:'名詞'},
{word:'神話',pos:'名詞'},{word:'伝説',pos:'名詞'},{word:'物語',pos:'名詞'},{word:'童話',pos:'名詞'},{word:'寓話',pos:'名詞'},
{word:'絵本',pos:'名詞'},{word:'手紙',pos:'名詞'},{word:'日記',pos:'名詞'},{word:'メモ',pos:'名詞'},{word:'写真',pos:'名詞'},
{word:'影絵',pos:'名詞'},{word:'水彩',pos:'名詞'},{word:'素描',pos:'名詞'},{word:'スケッチ',pos:'名詞'},{word:'色鉛筆',pos:'名詞'},
{word:'万華鏡',pos:'名詞'},{word:'望遠鏡',pos:'名詞'},{word:'双眼鏡',pos:'名詞'},{word:'虫眼鏡',pos:'名詞'},{word:'プリズム',pos:'名詞'},
{word:'白旗',pos:'名詞'},{word:'赤旗',pos:'名詞'},{word:'旗',pos:'名詞'},{word:'帆',pos:'名詞'},{word:'錨',pos:'名詞'},
{word:'舟',pos:'名詞'},{word:'船',pos:'名詞'},{word:'ボート',pos:'名詞'},{word:'筏',pos:'名詞'},{word:'浮き輪',pos:'名詞'},
{word:'雫',pos:'名詞'},{word:'飛沫',pos:'名詞'},{word:'水煙',pos:'名詞'},{word:'滝',pos:'名詞'},{word:'泉',pos:'名詞'},
{word:'井戸',pos:'名詞'},{word:'池',pos:'名詞'},{word:'湖',pos:'名詞'},{word:'沼',pos:'名詞'},{word:'湿地',pos:'名詞'},
{word:'渓谷',pos:'名詞'},{word:'峡谷',pos:'名詞'},{word:'峠',pos:'名詞'},{word:'尾根',pos:'名詞'},{word:'稜線',pos:'名詞'},
{word:'山頂',pos:'名詞'},{word:'山麓',pos:'名詞'},{word:'裾野',pos:'名詞'},{word:'野原',pos:'名詞'},{word:'畑',pos:'名詞'},
{word:'田んぼ',pos:'名詞'},{word:'里',pos:'名詞'},{word:'里山',pos:'名詞'},{word:'農村',pos:'名詞'},{word:'漁村',pos:'名詞'},
{word:'港町',pos:'名詞'},{word:'城下町',pos:'名詞'},{word:'路地',pos:'名詞'},{word:'横丁',pos:'名詞'},{word:'商店街',pos:'名詞'},
{word:'交差点',pos:'名詞'},{word:'信号',pos:'名詞'},{word:'歩道橋',pos:'名詞'},{word:'踏切',pos:'名詞'},{word:'線路',pos:'名詞'},
{word:'プラットフォーム',pos:'名詞'},{word:'ホーム',pos:'名詞'},{word:'改札',pos:'名詞'},{word:'終電',pos:'名詞'},{word:'始発',pos:'名詞'},
{word:'夜汽車',pos:'名詞'},{word:'汽笛',pos:'名詞'},{word:'車窓',pos:'名詞'},{word:'夜景',pos:'名詞'},{word:'地下鉄',pos:'名詞'},
{word:'空白',pos:'名詞'},{word:'余白',pos:'名詞'},{word:'すきま',pos:'名詞'},{word:'亀裂',pos:'名詞'},{word:'ひずみ',pos:'名詞'},
{word:'波長',pos:'名詞'},{word:'周波数',pos:'名詞'},{word:'振動',pos:'名詞'},{word:'振幅',pos:'名詞'},{word:'周期',pos:'名詞'},
{word:'節目',pos:'名詞'},{word:'分岐点',pos:'名詞'},{word:'転換点',pos:'名詞'},{word:'岐路',pos:'名詞'},{word:'選択',pos:'名詞'},
{word:'決断',pos:'名詞'},{word:'葛藤',pos:'名詞'},{word:'矛盾',pos:'名詞'},{word:'ジレンマ',pos:'名詞'},{word:'答え',pos:'名詞'},
{word:'問い',pos:'名詞'},{word:'謎',pos:'名詞'},{word:'真相',pos:'名詞'},{word:'核心',pos:'名詞'},{word:'本質',pos:'名詞'},
{word:'表面',pos:'名詞'},{word:'深層',pos:'名詞'},{word:'心の奥',pos:'名詞'},{word:'無意識',pos:'名詞'},{word:'潜在意識',pos:'名詞'},
{word:'トラウマ',pos:'名詞'},{word:'コンプレックス',pos:'名詞'},{word:'劣等感',pos:'名詞'},{word:'優越感',pos:'名詞'},{word:'罪悪感',pos:'名詞'},
{word:'使命感',pos:'名詞'},{word:'責任',pos:'名詞'},{word:'義務',pos:'名詞'},{word:'権利',pos:'名詞'},{word:'自由意志',pos:'名詞'},
{word:'存在意義',pos:'名詞'},{word:'アイデンティティ',pos:'名詞'},{word:'自己',pos:'名詞'},{word:'他者',pos:'名詞'},{word:'鏡像',pos:'名詞'},
// ===== 動詞追加 =====
{word:'気にする',pos:'動詞'},{word:'気にかける',pos:'動詞'},{word:'心配する',pos:'動詞'},{word:'安心する',pos:'動詞'},{word:'後悔する',pos:'動詞'},
{word:'反省する',pos:'動詞'},{word:'決意する',pos:'動詞'},{word:'諦める',pos:'動詞'},{word:'あがく',pos:'動詞'},{word:'もがく',pos:'動詞'},
{word:'あきらめない',pos:'動詞'},{word:'立ち向かう',pos:'動詞'},{word:'挑む',pos:'動詞'},{word:'挑戦する',pos:'動詞'},{word:'克服する',pos:'動詞'},
{word:'受け入れる',pos:'動詞'},{word:'拒む',pos:'動詞'},{word:'認める',pos:'動詞'},{word:'否定する',pos:'動詞'},{word:'肯定する',pos:'動詞'},
{word:'さまよう',pos:'動詞'},{word:'さすらう',pos:'動詞'},{word:'彷徨う',pos:'動詞'},{word:'漂泊する',pos:'動詞'},{word:'流浪する',pos:'動詞'},
{word:'旅する',pos:'動詞'},{word:'巡る',pos:'動詞'},{word:'駆ける',pos:'動詞'},{word:'駆け抜ける',pos:'動詞'},{word:'突き進む',pos:'動詞'},
{word:'這い上がる',pos:'動詞'},{word:'踏みしめる',pos:'動詞'},{word:'踏み越える',pos:'動詞'},{word:'乗り越す',pos:'動詞'},{word:'飛び越す',pos:'動詞'},
{word:'すり抜ける',pos:'動詞'},{word:'かいくぐる',pos:'動詞'},{word:'切り開く',pos:'動詞'},{word:'切り拓く',pos:'動詞'},{word:'道を拓く',pos:'動詞'},
{word:'分かる',pos:'動詞'},{word:'解かる',pos:'動詞'},{word:'気づかない',pos:'動詞'},{word:'見失う',pos:'動詞'},{word:'見極める',pos:'動詞'},
{word:'見抜く',pos:'動詞'},{word:'見透かす',pos:'動詞'},{word:'見渡す',pos:'動詞'},{word:'眺める',pos:'動詞'},{word:'観察する',pos:'動詞'},
{word:'記録する',pos:'動詞'},{word:'刻む',pos:'動詞'},{word:'刻み込む',pos:'動詞'},{word:'刻みつける',pos:'動詞'},{word:'焼き付ける',pos:'動詞'},
{word:'残す',pos:'動詞'},{word:'遺す',pos:'動詞'},{word:'伝え続ける',pos:'動詞'},{word:'語り継ぐ',pos:'動詞'},{word:'受け継ぐ',pos:'動詞'},
{word:'紡ぐ',pos:'動詞'},{word:'編む',pos:'動詞'},{word:'織る',pos:'動詞'},{word:'縫う',pos:'動詞'},{word:'彫る',pos:'動詞'},
{word:'刻む',pos:'動詞'},{word:'書く',pos:'動詞'},{word:'綴る',pos:'動詞'},{word:'記す',pos:'動詞'},{word:'詠む',pos:'動詞'},
{word:'奏する',pos:'動詞'},{word:'弾く',pos:'動詞'},{word:'吹く',pos:'動詞'},{word:'叩く',pos:'動詞'},{word:'弾き語る',pos:'動詞'},
{word:'口ずさむ',pos:'動詞'},{word:'鼻歌を歌う',pos:'動詞'},{word:'ハミングする',pos:'動詞'},{word:'リズムを刻む',pos:'動詞'},{word:'メロディを紡ぐ',pos:'動詞'},
// ===== 形容詞追加 =====
{word:'切り裂くような',pos:'形容詞'},{word:'息苦しい',pos:'形容詞'},{word:'息をのむ',pos:'形容詞'},{word:'心地よい',pos:'形容詞'},{word:'居心地悪い',pos:'形容詞'},
{word:'やるせない',pos:'形容詞'},{word:'やむを得ない',pos:'形容詞'},{word:'仕方ない',pos:'形容詞'},{word:'どうしようもない',pos:'形容詞'},{word:'避けられない',pos:'形容詞'},
{word:'逃れられない',pos:'形容詞'},{word:'抗えない',pos:'形容詞'},{word:'変えられない',pos:'形容詞'},{word:'止められない',pos:'形容詞'},{word:'消せない',pos:'形容詞'},
{word:'忘れられない',pos:'形容詞'},{word:'忘れたい',pos:'形容詞'},{word:'覚えていたい',pos:'形容詞'},{word:'伝えたい',pos:'形容詞'},{word:'届いてほしい',pos:'形容詞'},
{word:'眠れない',pos:'形容詞'},{word:'目が覚める',pos:'形容詞'},{word:'夢のような',pos:'形容詞'},{word:'現実離れした',pos:'形容詞'},{word:'非現実的な',pos:'形容詞'},
{word:'圧倒的な',pos:'形容詞'},{word:'絶対的な',pos:'形容詞'},{word:'相対的な',pos:'形容詞'},{word:'微妙な',pos:'形容詞'},{word:'繊細な',pos:'形容詞'},
{word:'大胆な',pos:'形容詞'},{word:'豪快な',pos:'形容詞'},{word:'華麗な',pos:'形容詞'},{word:'地味な',pos:'形容詞'},{word:'素朴な',pos:'形容詞'},
{word:'素直な',pos:'形容詞'},{word:'率直な',pos:'形容詞'},{word:'正直な',pos:'形容詞'},{word:'誠実な',pos:'形容詞'},{word:'不誠実な',pos:'形容詞'},
{word:'孤高な',pos:'形容詞'},{word:'崇高な',pos:'形容詞'},{word:'卑屈な',pos:'形容詞'},{word:'傲慢な',pos:'形容詞'},{word:'謙虚な',pos:'形容詞'},
];

// --- SKK辞書 ---
export let dict=[];
export async function loadDict(){
    try{
        const res=await fetch('SKK-JISYO.L');
        if(!res.ok)return;
        const txt=new TextDecoder('euc-jp').decode(await res.arrayBuffer());
        let n=0;
        for(let ln of txt.split('\n')){
            if(!ln||ln.startsWith(';'))continue;
            const sp=ln.indexOf(' ');if(sp<0)continue;
            const y=ln.slice(0,sp);if(!/^[ぁ-んー]+$/.test(y))continue;
            // っ吸収後の母音で登録
            const yy=y.replace(/[っ](?=[ぁ-ん])/g,'').replace(/[っ]/g,'');
            const v=pv(yy);if(!v.length)continue;
            for(const w of ln.slice(sp+1).split('/').filter(w=>w&&!w.startsWith(';')&&!w.startsWith('['))){
                const cw=w.replace(/;.*$/,'').trim();if(!cw)continue;
                dict.push({word:cw,s:v.length,v});if(++n>=80000)break;
            }
            if(n>=80000)break;
        }
    }catch(e){
        // 辞書なしで続行
    }
}